### PR TITLE
RAV4/RAV4H interface.py update

### PR DESCRIPTION
**Pull request by chicman**
Wheel base fine tuning
Can confirm SnG works in RAV4 andRAV4H. if/else removed.

Test drive over a month, works fine.

### CODE REVIEW

**Comment by chicman** [comment]
Wheel base fine tuning
Can confirm SnG works in RAV4 andRAV4H. if/else removed.

**Comment by rav4kumar** [comment]
do you have smartdsu? or pedal or additional hardware? because it does not work on my car.

**Comment by chicman** [comment]
> do you have smartdsu? or pedal or additional hardware? because it does not work on my car.

No pedal No additional HW, just C2, will work on my car.

**Comment by rav4kumar** [comment]
I will make stop and go hack param that you can turn on from op_edit. I am not convinced this is the best way will cause issue for different setup and I know for fact it throw error for ice rav4.

**Comment by chicman** [comment]
> I will make stop and go hack param that you can turn on from op_edit. I am not convinced this is the best way will cause issue for different setup and I know for fact it throw error for ice rav4.

Sure!

**Comment by chicman** [comment]
> I will make stop and go hack param that you can turn on from op_edit. I am not convinced this is the best way will cause issue for different setup and I know for fact it throw error for ice rav4.

Wondering what's "ice rav4"?

**Comment by chicman** [comment]
> I will make stop and go hack param that you can turn on from op_edit. I am not convinced this is the best way will cause issue for different setup and I know for fact it throw error for ice rav4.

I will remove the SnG if condition, update the wheel base only.
New PR after the new op_parma has inserted.

**Review by chicman — COMMENTED** [review]
remove SnG condition
Update wheel base fine tuning.

**Comment by rav4kumar** [comment]
thanks!

**Pull request merged**
